ok/web/app/__init__.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import
import logging
from time import time

from flask import Flask
from flask_cache import Cache
from werkzeug.contrib.cache import SimpleCache

app = Flask(__name__)
app.config.from_object('config')

loggers = [logging.getLogger('ok'), logging.getLogger('app')]
lh = logging.StreamHandler()
lh.setFormatter(logging.Formatter('%(asctime)s [%(levelname)s] %(name)s: %(message)s'))
for logger in loggers:
    logger.setLevel(logging.DEBUG)
    logger.addHandler(lh)

class DummyCache(SimpleCache):

    def __init__(self, _, config, args, kwargs):
        kwargs.update(dict(threshold=config['CACHE_THRESHOLD'], default_timeout=86400))
        super(DummyCache, self).__init__(*args, **kwargs)

    def get(self, key):
        try:
            expires, value = self._cache[key]
            if expires > time():
                return value
            else:
                print("Expired key evicted from cache: %s" % key)
        except KeyError:
            return None

    def add(self, key, value, timeout=None):
        if timeout is None:
            timeout = self.default_timeout
        self._prune()
        item = (time() + timeout, value)
        if key in self._cache:
            return False
        self._cache.setdefault(key, item)
        return True

    def set(self, key, value, timeout=None):
        if timeout is None:
            timeout = self.default_timeout
        self._prune()
        self._cache[key] = (time() + timeout, value)
        return True

cache = Cache(app, config={'CACHE_TYPE': 'app.DummyCache'})

def get_config(base_dir=None):
    import ok.dicts

    config = ok.dicts.main_options([] if not base_dir else ['', '-base-dir', base_dir])
    import os.path

    product_types_in_json_bin = config.product_types_in_json
    if '.bin' not in product_types_in_json_bin:
        product_types_in_json_bin = '%s.bin%s' % os.path.splitext(product_types_in_json_bin)
        if os.path.isfile(product_types_in_json_bin):
            config = config._replace(product_types_in_json=product_types_in_json_bin)

    config = config._replace(products_meta_in_csvname=os.path.join(config.baseline_dir, 'products_meta.csv'))
    return config

data_config = get_config()

from app.search.views import mod as search_module
app.register_blueprint(search_module)

ok/web/app/search/__init__.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function

ok/web/app/search/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function
from collections import OrderedDict, defaultdict

from flask import render_template, Blueprint, jsonify, request

from ok.utils import to_str
from ok.dicts.term import TypeTerm
from ok.query.find import find_products

from app import cache, data_config

mod = Blueprint('search', __name__, url_prefix='/search')


@cache.cached(key_prefix='_get_term_dict')
def get_term_dict():
    """@rtype: TypeTermDict"""
    term_dict = TypeTerm.term_dict.from_file(data_config.term_dict, verbose=True, skip_word_forms_validation=True)
    term_dict.print_stats()
    return term_dict


@mod.before_app_first_request
def init_data():
    get_term_dict()
    from ok.query.whoosh_contrib import indexes as ixs
    ixs.init_index()


@mod.route("/", methods=['GET', 'POST'])
def enter():
    try:
        q = request.form['q']
    except KeyError:
        q = request.args.get('q', '')

    if not q:
        entries = []
        facets = {}
    else:
        facet_fields = ['types', 'tail']
        with find_products(q, limit=None, return_fields=['pfqn', 'types', 'tail'], facet_fields=facet_fields) as rs:
            entries = [{'header': 'query', 'value': to_str(repr(rs.query))},
                       {'header': 'size', 'value': rs.size}]
            for pfqn, types, tail in rs.data:
                entry = {'pfqn': pfqn, 'score': rs.score,
                         'types': to_str(types), 'tail': to_str(tail),
                         'matched': to_str(rs._fetcher.current_match.matched_terms())}
                entries.append(entry)
            facets = defaultdict(OrderedDict)
            if rs.size > 0:
                for facet in facet_fields:
                    counts = rs.facet_counts(facet)
                    facets[facet].update(counts)

    return render_template('search/landing.html', q=q, entries=entries, product_list=[], facets=facets)


@mod.route("/suggest/json")
def suggest_json():
    q = request.args.get('term')
    with find_products(q, return_fields=['pfqn']) as rs:
        results = [('', to_str(repr(rs.query))), ('', 'Found %d results' % rs.size)]
        results.extend((pfqn, pfqn) for pfqn in rs.data)
    return jsonify({'results': [{'label': it[1], 'value': it[0]} for it in results]})


@mod.route("/product/summary/json")
def product_summary_json():
    q = request.args.get('q')
    results = [{'pfqn': q}]
    return jsonify({'results': results})

ok/web/app/templates/search/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='jquery-ui.css') }}">
    <script src="{{ url_for('static', filename='jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='jquery-ui.js') }}"></script>
</head>
<style>
.ui-autocomplete {
    max-height: 550px;
    overflow-y: auto;
    /* prevent horizontal scrollbar */
    overflow-x: hidden;
     width: 200px;
  }
  /* IE 6 doesn't support max-height
   * we use height instead, but this forces the menu to always be this tall
   */
  * html .ui-autocomplete {
  height: 100px;
  }

#wrapper {
    width: 1000px;
    border: 1px solid black;
    overflow: auto;
    }
#search-form {
    width: 500px;
    float: left;
    }
#product-list {
    border: 1px solid green;
    margin: 0 0 0 502px;
    }
#menu {
    position: relative;
    display: block;
    }
</style>

<body>
    <form action="{{ url_for('search.enter') }}" method="POST" class="search">
      <dl>
        <dt>What do you want?:
        <dd><input id="query" type="text" size="100" name="q" value="{{ q }}">
        <dd><input type="submit" value="What?">
      </dl>
    </form>

<div id="wrapper">
    <div id="search-form">
        <div id="menu" class="ui-front"></div>
        <ul class="entries">
          {% for entry in product_list %}
            <li>{{ entry.pfqn }}<br/>{{ entry.sqn }}|{{ entry.brand }}</li>
          {% else %}
            <li><em>...</em></li>
          {% endfor %}
          </ul>

        <div id="facets">
            <ul>
            {% for facet, counts in facets.items() %}
            <li>
                {{ facet }}
                <ul>
                    {% for value, count in counts|dictsort(by='value')|reverse %}
                        <li>{{ value }}: {{ count }}</li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div id="product-list">
        {% for entry in entries if entry.header %}
        <h2>{{ entry.header }}: {{ entry.value }}</h2>
        {% endfor %}
        <ul class="entries">
          {% for entry in entries if not entry.header %}
            {% if loop.index0 is divisibleby 10 %}
            <h2>...[{{ 'Results from %(start)d to %(end)d'|format(start=loop.index, end=(loop.index+9 if loop.index+9 < loop.length else loop.length+1)) }}]...</h2>
            {% endif %}
            <li>
                <a href="{{ url_for('search.enter') }}?q={{ entry.pfqn|urlencode }}"><h4>{{ entry.pfqn }} (<i>~{{ '%0.2f'|format(entry.score) }}</i>)</h4></a>
                {% if entry.types -%}
                    Types: {{ entry.types }}<br/>
                {% endif %}
                {% if entry.matched -%}
                    Matched: {{ entry.matched }}
                {% endif -%}
            </li>
          {% else %}
            <li><em>Unbelievable.  No entries here so far</em>
          {% endfor %}
          </ul>
    </div>
</div>

<script>
$( "#query" ).autocomplete({
    minLength: 3,
    appendTo: "menu",
    position: {of: "#menu"},
	source: function( request, response ) {
          $.getJSON( "{{ url_for('search.suggest_json') }}", {
            term: request.term
          }, function( data ) {
            var filtered = [];
            var count = 0;
            var last_top = ''
            var query_i = $( "#query" ).get()[0];
            for (var i = 0; i < data.results.length; i++) {
                count = 0;
                last_top = data.results[i]
                filtered.push(data.results[i]);
            }
            response( filtered );
            });
        },
    focus: function( event, ui ) {
          $.getJSON( "{{ url_for('search.product_summary_json') }}", {
            q: ui.item.value
          }, function( data ) {
            ul = $( "<ul/>" );
            $.each( data.results, function( index, product ) {
                li = $( '<li>' + product.pfqn + '</li>' ).appendTo(ul);
                if (product.brand) {
                    li.append( '<br/>' + product.sqn + '|' + product.brand );
                };
                });
            $( "#product-list" ).html( ul );
            });

        return false;
      },
    select: function( event, ui ) {
        $( "#query" ).val( ui.item.value );
        return false;
    },
})
.autocomplete( "instance" )._renderItem = function( ul, item ) {
      return $( "<li>" )
        .append( "<a><strong>" + item.label + "</strong></a>" )
        .appendTo( ul );
};
$( "#query" ).autocomplete( "instance" )._resizeMenu = function() {
        this.menu.element.outerWidth( 500 );
};
</script>

</body>
</html>